# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d618d2cc105f94263d7681bc5f5049b79d5c74fe6ee4ed3a2f3564f2475cc0438439810f6640c8510c036f0e2e0a708d56bf2afeead8f1ab213ab2a2c8bd5941

test:
  secret_key_base: f9665b66440e4d917b9891efde1e9e88a5d92eef688f3badf7b337dad3700dca2483087c54ea088757afd75b61c2f6ab191ac5f2c4640098526b25c271fef216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
